name: example_camera_image_plugin
description: "An example Flutter plugin project, for integrating with the 'camera_image_method_channel' plugin."
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera_image_method_channel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.example_camera_image_plugin
        pluginClass: ExampleCameraImagePlugin
      ios:
        pluginClass: ExampleCameraImagePlugin
