name: camera_image_method_channel
description: "A Flutter plugin that converts a CameraImage from the camera package, to a native pixel buffer representation via method channels."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.camera_image_method_channel
        pluginClass: CameraImageMethodChannelPlugin
      ios:
        pluginClass: CameraImageMethodChannelPlugin
