name: example_camera_image_plugin_example
description: "Demonstrates how to use the example_camera_image_plugin plugin."

publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  example_camera_image_plugin:
    path: ../
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  share_plus: ^7.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true